### ISSUE TITLE
Units tests fail on fresh install

### ISSUE THREAD

**Issue by corradomatt** [lucatume/idlikethis#3]
Looking at this example of codecept and WP I did a clean install of the WP unit test library and this plugin and when running the tests all unit tests fail. The integration tests all pass but the unit tests return the following error...

```
[PHPUnit\Framework\Exception]         
mysqli_query(): Couldn't fetch mysqli
```

**Comment by lucatume** [comment]
Hi there,

are you running all the tests at the same time using `codecept run`? If that's the case then know that, due to WordPress extensive use of globals and constants, is not recommended. Try to run each suite separately using `codecept run unit`, `codecept run acceptance` and so on.

**Comment by corradomatt** [comment]
ahh, yes. That did the trick! Thanks @lucatume for the fast response and all that you've done with WP testing. This seems like it'll make my testing life much easier.

**Comment by lucatume** [comment]
I very much hope so. Should you encounter another issue you are more than welcome to report it.
Happy coding and testing!
